import { UrbanParamsFilters, PesquisaUsoResult, UsoSearchResultItem } from "../utils/types";
import { RangeFilterValue } from "../ui/PriceRangeSlider";
export declare function isNAValue(val: any): boolean;
export declare function useProspectiveSearch(moduleData: Record<string, any[]>): {
    usosData: any[];
    cnaeData: any[];
    cnaeCatalogData: any[];
    usosPorZonaData: any[];
    parametrosUsoData: any[];
    parametrosZonasData: any[];
    parametrosPqaData: any[];
    useSearchTerm: string;
    setUseSearchTerm: import("react").Dispatch<import("react").SetStateAction<string>>;
    searchMode: "atividade" | "cnae" | "cnpj";
    setSearchMode: import("react").Dispatch<import("react").SetStateAction<"atividade" | "cnae" | "cnpj">>;
    useSearchResults: PesquisaUsoResult | null;
    selectedUse: UsoSearchResultItem | null;
    setSelectedUse: import("react").Dispatch<import("react").SetStateAction<UsoSearchResultItem | null>>;
    clearUseSearch: () => void;
    urbanParams: UrbanParamsFilters;
    updateUrbanParam: (param: string, value: RangeFilterValue) => void;
    removeUrbanParam: (param: string) => void;
    urbanParamsResults: any[];
    urbanParamsPqaResults: any[];
    clearUrbanParams: () => void;
    availableOptions: Record<string, number[]>;
    disabledUrbanParams: string[];
    pqaParams: UrbanParamsFilters;
    updatePqaParam: (param: string, value: RangeFilterValue) => void;
    removePqaParam: (param: string) => void;
    clearPqaParams: () => void;
    pqaOptions: Record<string, number[]>;
    areaImovel: [number, number] | null;
    updateAreaImovel: (newArea: [number, number] | null) => void;
    disabledPqaParams: string[];
    regrasZonamento: import("../utils/types").RegraZonamento | null;
    condicoesInstalacao: import("../utils/types").CondicaoInstalacao[];
    compatibleZones: any[];
    matchingZones: any[];
    compatiblePqas: any[];
    allPqaNames: any[];
    canSynthesize: boolean;
    synthesisMode: boolean;
    setSynthesisMode: import("react").Dispatch<import("react").SetStateAction<boolean>>;
};
//# sourceMappingURL=useProspectiveSearch.d.ts.map