base:
  domainName: api.mapa.urbis.sampa.br
components-api-gateway:
  domainName: api.mapa.urbis.sampa.br
  cm-acme-http-solver-name: cm-acme-http-solver-n7vxv
components-apps:
  domainName: api.mapa.urbis.sampa.br
ingress-nginx:
  controller:
    ingressClassResource:
      name: nginx-map
      default: false
      controllerValue: "k8s.io/ingress-nginx"
    service:
      externalTrafficPolicy: Local # Mudado para Local
      annotations:
        # Adiciona a anotação para a health probe do Azure LB
        # Note as aspas por causa dos caracteres especiais no nome da chave
        "service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path": "/healthz"
        #... outras anotações que você possa ter...