import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import { useProspectiveSearchContext } from "./ProspectiveSearchContext";
import { ResultsTable } from "./ui/ResultsTable";
import { SynthesisModal } from "./ui/SynthesisModal";
import { ModalExplicativo } from "./ui/ModalExplicativo";
import { NotesModal } from "./ui/NotesModal";
import { ScrollArea } from "@open-urbis/map-ui";
import { Layers, Info, Search, Check } from "lucide-react";
export function DynamicSystemResults() {
    const state = useProspectiveSearchContext();
    const [synthesisModalOpen, setSynthesisModalOpen] = React.useState(false);
    const [explicativoOpen, setExplicativoOpen] = React.useState(false);
    const [selectedNoteId, setSelectedNoteId] = React.useState(null);
    React.useEffect(() => {
        if (state.synthesisMode) {
            setSynthesisModalOpen(true);
        }
    }, [state.synthesisMode]);
    const { regrasZonamento, condicoesInstalacao, compatibleZones, compatiblePqas, allPqaNames, } = state;
    return (_jsxs("div", { className: "flex-1 bg-background h-full overflow-hidden flex flex-col relative min-w-0 z-10", children: [_jsx(ScrollArea, { className: "h-full w-full", children: _jsx("div", { className: "mx-auto flex h-full w-full max-w-[860px] flex-col p-4 md:p-6 lg:p-7", children: state.synthesisMode ? (_jsxs("div", { className: "animate-in fade-in slide-in-from-bottom-2 duration-500", children: [_jsxs("div", { className: "mb-10 flex justify-between items-end", children: [_jsxs("div", { children: [_jsxs("h2", { className: "text-2xl font-semibold  dark:text-white flex items-center gap-3", children: [_jsx(Layers, { className: "w-6 h-6 text-primary" }), "Zonamento compat\u00EDvel"] }), _jsx("p", { className: "  mt-2 text-sm font-medium", children: "Interse\u00E7\u00E3o entre atividades permitidas e par\u00E2metros urban\u00EDsticos." })] }), _jsxs("button", { onClick: () => setSynthesisModalOpen(true), className: "flex items-center gap-2 text-xs  hover:text-primary transition-colors font-semibold", children: [_jsx(Info, { className: "w-4 h-4" }), "Metodologia"] })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsxs("div", { className: "flex flex-col h-full bg-emerald-50/50 dark:bg-emerald-950/10 border border-emerald-100 dark:border-emerald-900/50 rounded-2xl overflow-hidden", children: [_jsxs("div", { className: "px-5 py-4 border-b border-emerald-100 dark:border-emerald-900/50 bg-emerald-100/50 dark:bg-emerald-900/20 flex items-center gap-3", children: [_jsx("div", { className: "p-1.5 bg-emerald-500 rounded-full text-white shadow-sm flex items-center justify-center", children: _jsx(Check, { className: "w-3 h-3", strokeWidth: 3 }) }), _jsx("h4", { className: "text-sm font-bold text-emerald-900 dark:text-emerald-400 tracking-tight", children: "Uso permitido direto" })] }), _jsx("div", { className: "p-6 flex-1 bg-white/50 dark:bg-slate-900/20", children: _jsxs("div", { className: "flex flex-wrap gap-2", children: [compatibleZones
                                                            .filter((z) => !regrasZonamento ||
                                                            regrasZonamento.simSemNota.includes(z))
                                                            .map((z) => (_jsx("span", { className: "dark:bg-slate-800 px-3 py-1.5 text-xs font-semibold shadow-sm border border-emerald-200 dark:border-emerald-800/60 text-emerald-800 dark:text-emerald-300 rounded-lg", children: z }, z))), compatibleZones.filter((z) => !regrasZonamento ||
                                                            regrasZonamento.simSemNota.includes(z)).length === 0 && (_jsx("span", { className: "text-xs text-emerald-600/60 dark:text-emerald-500/50 font-medium", children: "Nenhuma zona encontrada" }))] }) })] }), _jsxs("div", { className: "flex flex-col h-full bg-blue-50/50 dark:bg-blue-950/10 border border-blue-100 dark:border-blue-900/50 rounded-2xl overflow-hidden", children: [_jsxs("div", { className: "px-5 py-4 border-b border-blue-100 dark:border-blue-900/50 bg-blue-100/50 dark:bg-blue-900/20 flex items-center gap-3", children: [_jsx("div", { className: "p-1.5 bg-blue-500 rounded-full text-white shadow-sm flex items-center justify-center", children: _jsx(Info, { className: "w-3 h-3", strokeWidth: 3 }) }), _jsx("h4", { className: "text-sm font-bold text-blue-900 dark:text-blue-400 tracking-tight", children: "Uso com restri\u00E7\u00F5es" })] }), _jsx("div", { className: "p-6 flex-1 bg-white/50 dark:bg-slate-900/20", children: _jsxs("div", { className: "flex flex-wrap gap-2", children: [compatibleZones
                                                            .filter((z) => regrasZonamento &&
                                                            Object.values(regrasZonamento.simComNota)
                                                                .flat()
                                                                .includes(z))
                                                            .map((z) => (_jsx("span", { className: "bg-white dark:bg-slate-800 px-3 py-1.5 text-xs font-semibold shadow-sm border border-blue-200 dark:border-blue-800/60 text-blue-800 dark:text-blue-300 rounded-lg", children: z }, z))), compatibleZones.filter((z) => regrasZonamento &&
                                                            Object.values(regrasZonamento.simComNota)
                                                                .flat()
                                                                .includes(z)).length === 0 && (_jsx("span", { className: "text-xs text-blue-600/60 dark:text-blue-500/50 font-medium", children: "Nenhuma zona encontrada" }))] }) })] })] })] })) : state.selectedUse ||
                        Object.keys(state.urbanParams).length > 0 ||
                        Object.keys(state.pqaParams).length > 0 ? (_jsxs("div", { className: "flex flex-col gap-6 pb-8", children: [state.selectedUse && (_jsx(ResultsTable, { selectedUse: state.selectedUse, regrasZonamento: regrasZonamento, condicoesInstalacao: condicoesInstalacao, 
                                // Do not filter by urban params here, show all zones relevant to the use
                                filteredZones: undefined, compatiblePqas: [], allPqaNames: [], hasPqaFilters: Object.keys(state.pqaParams).length > 0, hasUrbanFilters: Object.keys(state.urbanParams).length > 0, hasAreaFilter: state.areaImovel !== null, setExplicativoOpen: setExplicativoOpen, setSelectedNoteId: setSelectedNoteId })), (Object.keys(state.urbanParams).length > 0 ||
                                Object.keys(state.pqaParams).length > 0) && (_jsx(ResultsTable, { selectedUse: null, regrasZonamento: null, condicoesInstalacao: [], filteredZones: state.matchingZones, compatiblePqas: compatiblePqas, allPqaNames: allPqaNames, hasPqaFilters: Object.keys(state.pqaParams).length > 0, hasUrbanFilters: Object.keys(state.urbanParams).length > 0, hasAreaFilter: state.areaImovel !== null, setExplicativoOpen: setExplicativoOpen, setSelectedNoteId: setSelectedNoteId }))] })) : (_jsx("div", { className: "flex h-full w-full animate-in fade-in duration-700 items-center justify-center py-20 text-center", children: _jsxs("div", { className: "max-w-sm rounded-[28px] border border-slate-200/80 bg-white/90 px-8 py-10 shadow-sm dark:border-slate-800 dark:bg-slate-950/80", children: [_jsx(Search, { className: "mx-auto mb-6 h-12 w-12 text-slate-400", strokeWidth: 1.2 }), _jsx("h3", { className: "mb-2 text-base font-semibold text-gray-900 dark:text-slate-100", children: "Nenhum uso selecionado" }), _jsx("p", { className: "max-w-[280px] text-sm font-normal leading-relaxed text-gray-500 dark:text-slate-400", children: "Selecione uma atividade na barra lateral para ver a viabilidade, os par\u00E2metros t\u00E9cnicos e as notas aplic\u00E1veis nesta zona." })] }) })) }) }), _jsx(SynthesisModal, { isOpen: synthesisModalOpen, onClose: () => setSynthesisModalOpen(false) }), _jsx(ModalExplicativo, { isOpen: explicativoOpen, onClose: () => setExplicativoOpen(false), regrasZonamento: regrasZonamento, condicoesInstalacao: condicoesInstalacao, hasCnaeUsed: state.searchMode === "cnae" || !!state.selectedUse?.cnaeOriginario, hasUrbanFilters: Object.keys(state.urbanParams).length > 0, hasPqaFilters: Object.keys(state.pqaParams).length > 0, hasAreaFilter: state.areaImovel !== null }), _jsx(NotesModal, { notaId: selectedNoteId || "", isOpen: !!selectedNoteId, onClose: () => setSelectedNoteId(null) })] }));
}
