import React, { ReactNode } from "react";
import { useProspectiveSearch } from "./hooks/useProspectiveSearch";
export type ProspectiveSearchState = ReturnType<typeof useProspectiveSearch>;
export declare const ProspectiveSearchContext: React.Context<{
    usosData: any[];
    cnaeData: any[];
    cnaeCatalogData: any[];
    usosPorZonaData: any[];
    parametrosUsoData: any[];
    parametrosZonasData: any[];
    parametrosPqaData: any[];
    useSearchTerm: string;
    setUseSearchTerm: React.Dispatch<React.SetStateAction<string>>;
    searchMode: "atividade" | "cnae" | "cnpj";
    setSearchMode: React.Dispatch<React.SetStateAction<"atividade" | "cnae" | "cnpj">>;
    useSearchResults: import("./utils/types").PesquisaUsoResult | null;
    selectedUse: import("./utils/types").UsoSearchResultItem | null;
    setSelectedUse: React.Dispatch<React.SetStateAction<import("./utils/types").UsoSearchResultItem | null>>;
    clearUseSearch: () => void;
    urbanParams: import("./utils/types").UrbanParamsFilters;
    updateUrbanParam: (param: string, value: import("./ui/PriceRangeSlider").RangeFilterValue) => void;
    removeUrbanParam: (param: string) => void;
    urbanParamsResults: any[];
    urbanParamsPqaResults: any[];
    clearUrbanParams: () => void;
    availableOptions: Record<string, number[]>;
    disabledUrbanParams: string[];
    pqaParams: import("./utils/types").UrbanParamsFilters;
    updatePqaParam: (param: string, value: import("./ui/PriceRangeSlider").RangeFilterValue) => void;
    removePqaParam: (param: string) => void;
    clearPqaParams: () => void;
    pqaOptions: Record<string, number[]>;
    areaImovel: [number, number] | null;
    updateAreaImovel: (newArea: [number, number] | null) => void;
    disabledPqaParams: string[];
    regrasZonamento: import("./utils/types").RegraZonamento | null;
    condicoesInstalacao: import("./utils/types").CondicaoInstalacao[];
    compatibleZones: any[];
    matchingZones: any[];
    compatiblePqas: any[];
    allPqaNames: any[];
    canSynthesize: boolean;
    synthesisMode: boolean;
    setSynthesisMode: React.Dispatch<React.SetStateAction<boolean>>;
} | undefined>;
export declare function ProspectiveSearchProvider({ moduleData, children, }: {
    moduleData: Record<string, any[]>;
    children: ReactNode;
}): import("react/jsx-runtime").JSX.Element;
export declare function useProspectiveSearchContext(): any;
//# sourceMappingURL=ProspectiveSearchContext.d.ts.map