export const googleRecaptchaErrorCodeDictionary = {
  'missing-input-secret': 'recaptcha.missing.secret',
  'invalid-input-secret': 'recaptcha.invalid.secret',
  'missing-input-response': 'recaptcha.missing.response',
  'invalid-input-response': 'recaptcha.invalid.response',
  'bad-request': 'recaptcha.bad.request',
  'timeout-or-duplicate': 'recaptcha.timeout.duplicate',
  'unknown-error': 'recaptcha.unknown.error',
  'forbidden-action': 'recaptcha.forbidden.action',
  'low-score': 'recaptcha.low.score',
  'invalid-keys': 'recaptcha.invalid.keys',
  'network-error': 'recaptcha.network.error',
  'site-mismatch': 'recaptcha.site.mismatch',
  'browser-error': 'recaptcha.browser.error',
};
