apiVersion: apps/v1
kind: Deployment
metadata:
  name: urbis-map-storage
  namespace: urbis-map
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urbis-map-storage
  template:
    metadata:
      labels:
        app: urbis-map-storage
    spec:
      containers:
      - name: urbis-map-storage
        image: andrewgaul/s3proxy:latest
        ports:
        - containerPort: 8080
        env:
        - name: S3PROXY_AUTHORIZATION
          value: "aws-v2-or-v4"
        - name: S3PROXY_IDENTITY
          value: "***REMOVED***"
        - name: S3PROXY_CREDENTIAL
          value: "***REMOVED***"
        - name: JCLOUDS_IDENTITY
          value: "slui"
        - name: JCLOUDS_CREDENTIAL
          value: ***REMOVED***
        - name: JCLOUDS_ENDPOINT
          value: "https://***REMOVED***"
        - name: JCLOUDS_PROVIDER
          value: azureblob
        - name: JCLOUDS_AZUREBLOB_AUTH
          value: "azureKey"
        - name: S3PROXY_ENDPOINT
          value: "http://0.0.0.0:8080"
        - name: S3PROXY_CORS_ALLOW_ALL
          value: "true"