import { ConfigService } from '@nestjs/config';
import { ClientMetadata } from 'oidc-provider';

export const buildClientsDataSource = (
  configService: ConfigService,
): ClientMetadata[] => {
  const secret = configService.get('auth.secret');
  return [
    {
      application_type: 'web',
      client_id: '0375600b-cd37-4b89-82e1-68fd374b83e8',
      client_secret: secret,
      redirect_uris: [
        'http://localhost:4200',
        'http://localhost:4200/callback',
        'https://accounts.mapa.urbis.sampa.br',
        'https://accounts.mapa.urbis.sampa.br/callback',
        'http://conta.urbis.sampa.br/callback',
        'https://conta.urbis.sampa.br/callback',
        'http://mapa.urbis.sampa.br/callback',
        'http://mapa.urbis.sampa.br/silent-renew.html',
        'https://mapa.urbis.sampa.br',
        'http://mapa.urbis.sampa.br/callback',
        'https://mapa.urbis.sampa.br',
        'http://urbis.sampa.br/callback',
        'http://mapa.urbis.sampa.br/callback',

        // ─────────────── duplicatas com .prefeitura.sp.gov.br ───────────────
        'https://accounts.mapa.urbis.prefeitura.sp.gov.br',
        'https://accounts.mapa.urbis.prefeitura.sp.gov.br/callback',
        'http://conta.urbis.prefeitura.sp.gov.br/callback',
        'https://conta.urbis.prefeitura.sp.gov.br/callback',
        'http://mapa.urbis.prefeitura.sp.gov.br/callback',
        'http://mapa.urbis.prefeitura.sp.gov.br/silent-renew.html',
        'https://mapa.urbis.prefeitura.sp.gov.br',
        'http://mapa.urbis.prefeitura.sp.gov.br/callback',
        'https://mapa.urbis.prefeitura.sp.gov.br',
        'http://urbis.prefeitura.sp.gov.br/callback',
        'http://mapa.urbis.prefeitura.sp.gov.br/callback',
      ],
      response_types: ['code'],
      grant_types: ['refresh_token', 'authorization_code'],
      post_logout_redirect_uris: [
        'http://localhost:4200',
        'http://localhost:4200/callback',
        'https://accounts.mapa.urbis.sampa.br',
        'https://accounts.mapa.urbis.sampa.br/callback',
        'https://conta.urbis.sampa.br',
        'https://conta.urbis.sampa.br/callback',
        'http://mapa.urbis.sampa.br/silent-renew.html',
        'http://mapa.urbis.sampa.br/callback',
        'https://mapa.urbis.sampa.br',
        'http://mapa.urbis.sampa.br/callback',
        'https://mapa.urbis.sampa.br',
        'http://urbis.sampa.br/callback',
        'http://mapa.urbis.sampa.br/callback',

        // ─────────────── duplicatas com .prefeitura.sp.gov.br ───────────────
        'https://accounts.mapa.urbis.prefeitura.sp.gov.br',
        'https://accounts.mapa.urbis.prefeitura.sp.gov.br/callback',
        'https://conta.urbis.prefeitura.sp.gov.br',
        'https://conta.urbis.prefeitura.sp.gov.br/callback',
        'http://mapa.urbis.prefeitura.sp.gov.br/silent-renew.html',
        'http://mapa.urbis.prefeitura.sp.gov.br/callback',
        'https://mapa.urbis.prefeitura.sp.gov.br',
        'http://mapa.urbis.prefeitura.sp.gov.br/callback',
        'https://mapa.urbis.prefeitura.sp.gov.br',
        'http://urbis.prefeitura.sp.gov.br/callback',
        'http://mapa.urbis.prefeitura.sp.gov.br/callback',
        'http://localhost:3000/auth/global-logout',
        'https://api.mapa.urbis.prefeitura.sp.gov.br/auth/global-logout',
      ],
      token_endpoint_auth_method: 'none',
    },
    {
      application_type: 'web',
      client_id: '94a86322-269e-44df-803a-534c0382215d',
      client_secret: secret,
      redirect_uris: [
        'http://localhost:5173',
        'http://localhost:5173/callback',
        'http://localhost:5173/silent-renew.html',
        'https://app.atlascli.io',
        'https://app.atlascli.io/callback',
        'https://app.atlascli.io/silent-renew.html',
        'https://mapa.urbis.sampa.br',
        'https://mapa.urbis.sampa.br/callback',
        'https://mapa.urbis.sampa.br/silent-renew.html',
        'http://mapa.urbis.sampa.br/callback',
        'https://mapa.urbis.sampa.br',
        'http://mapa.urbis.sampa.br/callback',
        'https://mapa.urbis.sampa.br',

        // ─────────────── duplicatas com .prefeitura.sp.gov.br ───────────────
        'https://mapa.urbis.prefeitura.sp.gov.br',
        'https://mapa.urbis.prefeitura.sp.gov.br/callback',
        'https://mapa.urbis.prefeitura.sp.gov.br/silent-renew.html',
        'http://mapa.urbis.prefeitura.sp.gov.br/callback',
        'https://mapa.urbis.prefeitura.sp.gov.br',
        'http://mapa.urbis.prefeitura.sp.gov.br/callback',
        'https://mapa.urbis.prefeitura.sp.gov.br',
      ],
      response_types: ['code'],
      grant_types: ['refresh_token', 'authorization_code'],
      post_logout_redirect_uris: [
        'http://localhost:5173',
        'http://localhost:5173/callback',
        'http://localhost:5173/silent-renew.html',
        'https://app.atlascli.io',
        'https://app.atlascli.io/callback',
        'https://app.atlascli.io/silent-renew.html',
        'https://mapa.urbis.sampa.br',
        'https://mapa.urbis.sampa.br/callback',
        'https://mapa.urbis.sampa.br/silent-renew.html',
        'http://mapa.urbis.sampa.br/callback',
        'https://mapa.urbis.sampa.br',
        'http://mapa.urbis.sampa.br/callback',
        'https://mapa.urbis.sampa.br',

        // ─────────────── duplicatas com .prefeitura.sp.gov.br ───────────────
        'https://mapa.urbis.prefeitura.sp.gov.br',
        'https://mapa.urbis.prefeitura.sp.gov.br/callback',
        'https://mapa.urbis.prefeitura.sp.gov.br/silent-renew.html',
        'http://mapa.urbis.prefeitura.sp.gov.br/callback',
        'https://mapa.urbis.prefeitura.sp.gov.br',
        'http://mapa.urbis.prefeitura.sp.gov.br/callback',
        'https://mapa.urbis.prefeitura.sp.gov.br',
        'http://localhost:3000/auth/global-logout',
        'https://api.mapa.urbis.prefeitura.sp.gov.br/auth/global-logout',
      ],
      token_endpoint_auth_method: 'none',
    },
  ];
};
