import { LayerSchemaColors } from 'layer-schemas/entities/layer-schema-color.entity';
import { LayerSchema } from 'layer-schemas/entities/layer-schema.entity';
import {
  LayerSchemaClickActionEnum,
  LayerSchemaColorTypeEnum,
  LayerSchemaTypeEnum,
} from 'layer-schemas/enums/layer-schema.enum';

export const layerSchemaColors: LayerSchemaColors[] = [
  // Para zeis_pde
  {
    color: [196, 80, 80, 240],
    pattern: 'full',
    label: 'ZEIS-1',
    value: 'ZEIS-1',
    layerSchemaId: 'zeis_pde',
  },
  {
    color: [54, 125, 169, 240],
    pattern: 'full',
    label: 'ZEIS-2',
    value: 'ZEIS-2',
    layerSchemaId: 'zeis_pde',
  },
  {
    color: [65, 156, 139, 240],
    pattern: 'full',
    label: 'ZEIS-3',
    value: 'ZEIS-3',
    layerSchemaId: 'zeis_pde',
  },
  {
    color: [164, 89, 164, 240],
    pattern: 'full',
    label: 'ZEIS-4',
    value: 'ZEIS-4',
    layerSchemaId: 'zeis_pde',
  },
  {
    color: [241, 127, 4, 240],
    pattern: 'full',
    label: 'ZEIS-5',
    value: 'ZEIS-5',
    layerSchemaId: 'zeis_pde',
  },

  // Para eixos
  {
    color: [136, 144, 173, 240],
    pattern: 'full',
    label: 'Area de Influencia',
    value: 'Area de Influencia',
    layerSchemaId: 'eixos',
  },
  {
    color: [201, 186, 119, 240],
    pattern: 'full',
    label: 'Area de Influencia (2016)',
    value: 'Area de Influencia (2016)',
    layerSchemaId: 'eixos',
  },

  // Para macroareas
  {
    color: [127, 1, 0, 240],
    pattern: 'full',
    label: 'Macroarea de Estruturacao Metropolitana',
    value: 'Macroarea de Estruturacao Metropolitana',
    layerSchemaId: 'macroareas',
  },
  {
    color: [154, 89, 89, 240],
    pattern: 'full',
    label: 'Macroarea de Urbanizacao Consolidada',
    value: 'Macroarea de Urbanizacao Consolidada',
    layerSchemaId: 'macroareas',
  },
  {
    color: [210, 99, 28, 240],
    pattern: 'full',
    label: 'Macroarea de Qualificacao da Urbanizacao',
    value: 'Macroarea de Qualificacao da Urbanizacao',
    layerSchemaId: 'macroareas',
  },
  {
    color: [244, 191, 3, 240],
    pattern: 'full',
    label: 'Macroarea de Reducao da Vulnerabilidade Urbana',
    value: 'Macroarea de Reducao da Vulnerabilidade Urbana',
    layerSchemaId: 'macroareas',
  },
  {
    color: [250, 236, 176, 240],
    pattern: 'full',
    label:
      'Macroarea de Reducao da Vulnerabilidade Urbana e Recuperacao Ambiental',
    value:
      'Macroarea de Reducao da Vulnerabilidade Urbana e Recuperacao Ambiental',
    layerSchemaId: 'macroareas',
  },
  {
    color: [192, 212, 167, 240],
    pattern: 'full',
    label: 'Macroarea de Controle e Qualificacao Urbana e Ambiental',
    value: 'Macroarea de Controle e Qualificacao Urbana e Ambiental',
    layerSchemaId: 'macroareas',
  },
  {
    color: [108, 162, 150, 240],
    pattern: 'full',
    label: 'Macroarea de Contencao Urbana e Uso Sustentavel',
    value: 'Macroarea de Contencao Urbana e Uso Sustentavel',
    layerSchemaId: 'macroareas',
  },
  {
    color: [33, 89, 86, 240],
    pattern: 'full',
    label: 'Macroarea de Preservacao dos Ecossistemas Naturais',
    value: 'Macroarea de Preservacao dos Ecossistemas Naturais',
    layerSchemaId: 'macroareas',
  },

  // Para macrozonas
  {
    color: [190, 190, 190, 240],
    pattern: 'full',
    label: 'Macrozona de Estruturacao e Qualificacao Urbana',
    value: 'Macrozona de Estruturacao e Qualificacao Urbana',
    layerSchemaId: 'macrozonas',
  },
  {
    color: [50, 130, 138, 240],
    pattern: 'full',
    label: 'Macrozona de Protecao e Recuperacao Ambiental',
    value: 'Macrozona de Protecao e Recuperacao Ambiental',
    layerSchemaId: 'macrozonas',
  },

  // Para setores_subsetores
  {
    color: [140, 1, 0, 240],
    pattern: 'full',
    label: 'Arco Tiete',
    value: 'Arco Tiete',
    layerSchemaId: 'setores_subsetores',
  },
  {
    color: [205, 3, 0, 240],
    pattern: 'full',
    label: 'Arco Tamanduatei',
    value: 'Arco Tamanduatei',
    layerSchemaId: 'setores_subsetores',
  },
  {
    color: [238, 64, 0, 240],
    pattern: 'full',
    label: 'Arco Leste',
    value: 'Arco Leste',
    layerSchemaId: 'setores_subsetores',
  },
  {
    color: [205, 79, 57, 240],
    pattern: 'full',
    label: 'Arco Pinheiros',
    value: 'Arco Pinheiros',
    layerSchemaId: 'setores_subsetores',
  },
  {
    color: [241, 99, 72, 240],
    pattern: 'full',
    label: 'Faria Lima-Agua Espraiada-Chucri Zaidan',
    value: 'Faria Lima-Agua Espraiada-Chucri Zaidan',
    layerSchemaId: 'setores_subsetores',
  },
  {
    color: [244, 160, 122, 240],
    pattern: 'full',
    label: 'Arco Jurubatuba',
    value: 'Arco Jurubatuba',
    layerSchemaId: 'setores_subsetores',
  },
  {
    color: [252, 251, 205, 240],
    pattern: 'full',
    label: 'Avenida Cupece',
    value: 'Avenida Cupece',
    layerSchemaId: 'setores_subsetores',
  },
  {
    color: [238, 234, 191, 240],
    pattern: 'full',
    label: 'Noroeste',
    value: 'Noroeste',
    layerSchemaId: 'setores_subsetores',
  },
  {
    color: [219, 205, 116, 240],
    pattern: 'full',
    label: 'Arco Jacu-Pessego',
    value: 'Arco Jacu-Pessego',
    layerSchemaId: 'setores_subsetores',
  },
  {
    color: [167, 155, 88, 240],
    pattern: 'full',
    label: 'Fernao Dias',
    value: 'Fernao Dias',
    layerSchemaId: 'setores_subsetores',
  },
  {
    color: [161, 62, 54, 240],
    pattern: 'full',
    label: 'Centro',
    value: 'Centro',
    layerSchemaId: 'setores_subsetores',
  },

  // Para zoneamento_geral
  {
    color: [160, 160, 160, 240],
    pattern: 'full',
    label: 'Zona Urbana',
    value: 'Zona Urbana',
    layerSchemaId: 'zoneamento_geral',
  },
  {
    color: [146, 74, 0, 240],
    pattern: 'full',
    label: 'Zona Rural',
    value: 'Zona Rural',
    layerSchemaId: 'zoneamento_geral',
  },

  // Para zoneamento_lei_16402_18177
  {
    color: [223, 253, 178, 240],
    pattern: 'full',
    label: 'AC-1',
    value: 'AC-1',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [223, 253, 178, 240],
    pattern: 'dots',
    label: 'AC-2',
    value: 'AC-2',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [208, 234, 197, 240],
    pattern: 'full',
    label: 'Praça/Canteiro',
    value: 'Praça/Canteiro',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [173, 160, 152, 240],
    pattern: 'full',
    label: 'ZC',
    value: 'ZC',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [173, 160, 152, 240],
    pattern: 'dots',
    label: 'ZCa',
    value: 'ZCa',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [207, 178, 161, 240],
    pattern: 'full',
    label: 'ZC-ZEIS',
    value: 'ZC-ZEIS',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [137, 142, 189, 240],
    pattern: 'full',
    label: 'ZCOR-1',
    value: 'ZCOR-1',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [129, 186, 226, 240],
    pattern: 'full',
    label: 'ZCOR-2',
    value: 'ZCOR-2',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [181, 207, 231, 240],
    pattern: 'full',
    label: 'ZCOR-3',
    value: 'ZCOR-3',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [154, 190, 193, 240],
    pattern: 'full',
    label: 'ZCORa',
    value: 'ZCORa',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [181, 146, 177, 240],
    pattern: 'full',
    label: 'ZDE-1',
    value: 'ZDE-1',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [208, 175, 185, 240],
    pattern: 'full',
    label: 'ZDE-2',
    value: 'ZDE-2',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [219, 206, 159, 240],
    pattern: 'full',
    label: 'ZEIS-1',
    value: 'ZEIS-1',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [254, 208, 155, 240],
    pattern: 'full',
    label: 'ZEIS-2',
    value: 'ZEIS-2',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [255, 230, 170, 240],
    pattern: 'full',
    label: 'ZEIS-3',
    value: 'ZEIS-3',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [255, 239, 195, 240],
    pattern: 'full',
    label: 'ZEIS-4',
    value: 'ZEIS-4',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [255, 249, 221, 240],
    pattern: 'full',
    label: 'ZEIS-5',
    value: 'ZEIS-5',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [212, 159, 148, 240],
    pattern: 'full',
    label: 'ZEM',
    value: 'ZEM',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [227, 192, 169, 240],
    pattern: 'hatch-1x',
    label: 'ZEMP',
    value: 'ZEMP',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [145, 170, 149, 240],
    pattern: 'full',
    label: 'ZEP',
    value: 'ZEP',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [167, 211, 186, 240],
    pattern: 'full',
    label: 'ZEPAM',
    value: 'ZEPAM',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [255, 239, 195, 240],
    pattern: 'hatch-cross',
    label: 'ZER-1',
    value: 'ZER-1',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [255, 225, 158, 240],
    pattern: 'hatch-1x',
    label: 'ZER-2',
    value: 'ZER-2',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [255, 255, 153, 240],
    pattern: 'dots',
    label: 'ZERa',
    value: 'ZERa',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [189, 138, 140, 240],
    pattern: 'full',
    label: 'ZEU',
    value: 'ZEU',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [189, 138, 140, 240],
    pattern: 'dots',
    label: 'ZEUa',
    value: 'ZEUa',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [196, 158, 157, 240],
    pattern: 'hatch-1x',
    label: 'ZEUP',
    value: 'ZEUP',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [197, 184, 184, 240],
    pattern: 'dots',
    label: 'ZEUPa',
    value: 'ZEUPa',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [206, 206, 206, 240],
    pattern: 'full',
    label: 'ZM',
    value: 'ZM',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [217, 217, 217, 240],
    pattern: 'dots',
    label: 'ZMa',
    value: 'ZMa',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [186, 186, 186, 240],
    pattern: 'full',
    label: 'ZMIS',
    value: 'ZMIS',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [232, 232, 232, 240],
    pattern: 'full',
    label: 'ZMISa',
    value: 'ZMISa',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [224, 218, 197, 240],
    pattern: 'full',
    label: 'ZOE',
    value: 'ZOE',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [176, 193, 171, 240],
    pattern: 'full',
    label: 'ZPDS',
    value: 'ZPDS',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [200, 206, 175, 240],
    pattern: 'full',
    label: 'ZPDSr',
    value: 'ZPDSr',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [161, 154, 181, 240],
    pattern: 'full',
    label: 'ZPI-1',
    value: 'ZPI-1',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [212, 195, 221, 240],
    pattern: 'full',
    label: 'ZPI-2',
    value: 'ZPI-2',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [255, 255, 153, 240],
    pattern: 'full',
    label: 'ZPR',
    value: 'ZPR',
    layerSchemaId: 'zoneamento_lei_16402_18177',
  },
  {
    color: [153, 203, 255, 120],
    label: 'default',
    layerSchemaId: 'distrito_municipal',
    type: LayerSchemaColorTypeEnum.FILL,
  },
  {
    color: [153, 203, 255, 255],
    label: 'default',
    layerSchemaId: 'distrito_municipal',
    type: LayerSchemaColorTypeEnum.TEXT,
  },
  {
    color: [0, 0, 0, 120],
    label: 'default',
    layerSchemaId: 'distrito_municipal',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [57, 118, 29, 175],
    label: 'default',
    layerSchemaId: 'lotes',
  },
  {
    color: [0, 0, 0, 255],
    label: 'default',
    layerSchemaId: 'zeis_pde',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [255, 255, 255, 255],
    label: 'default',
    layerSchemaId: 'aguas_correntes_estimadas',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [65, 120, 216, 240],
    label: 'default',
    layerSchemaId: 'aguas_correntes_estimadas',
  },
  {
    color: [65, 120, 216, 240],
    label: 'default',
    layerSchemaId: 'aguas_correntes_estimadas',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [255, 255, 255, 255],
    label: 'default',
    layerSchemaId: 'aguas_correntes_ou_dormentes',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [56, 85, 204, 240],
    label: 'default',
    layerSchemaId: 'aguas_correntes_ou_dormentes',
  },
  {
    color: [56, 85, 204, 240],
    label: 'default',
    layerSchemaId: 'aguas_correntes_ou_dormentes',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [0, 0, 0, 255],
    label: 'default',
    layerSchemaId: 'areas_contaminadas',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [180, 95, 6, 240],
    label: 'default',
    layerSchemaId: 'areas_contaminadas',
  },
  {
    color: [180, 95, 6, 240],
    label: 'default',
    layerSchemaId: 'areas_contaminadas',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [255, 255, 255, 255],
    label: 'default',
    layerSchemaId: 'eixos',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [255, 255, 255, 255],
    label: 'default',
    layerSchemaId: 'macroareas',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [255, 255, 255, 255],
    label: 'default',
    layerSchemaId: 'macrozonas',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [255, 255, 255, 255],
    label: 'default',
    layerSchemaId: 'minianel_viario',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [217, 234, 211, 240],
    label: 'default',
    layerSchemaId: 'minianel_viario',
  },
  {
    color: [217, 234, 211, 240],
    label: 'default',
    layerSchemaId: 'minianel_viario',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [0, 0, 0, 255],
    label: 'default',
    layerSchemaId: 'pracas_e_canteiros',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [147, 196, 125, 240],
    label: 'default',
    layerSchemaId: 'pracas_e_canteiros',
  },
  {
    color: [147, 196, 125, 240],
    label: 'default',
    layerSchemaId: 'pracas_e_canteiros',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [255, 255, 255, 255],
    label: 'default',
    layerSchemaId: 'restricoes_geotecnicas',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [153, 2, 0, 240],
    label: 'default',
    layerSchemaId: 'restricoes_geotecnicas',
  },
  {
    color: [153, 2, 0, 240],
    label: 'default',
    layerSchemaId: 'restricoes_geotecnicas',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [255, 255, 255, 255],
    label: 'default',
    layerSchemaId: 'risco_geologico',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [255, 0, 0, 240],
    label: 'default',
    layerSchemaId: 'risco_geologico',
  },
  {
    color: [255, 0, 0, 240],
    label: 'default',
    layerSchemaId: 'risco_geologico',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [255, 255, 255, 255],
    label: 'default',
    layerSchemaId: 'risco_hidrologico',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [204, 0, 1, 240],
    label: 'default',
    layerSchemaId: 'risco_hidrologico',
  },
  {
    color: [204, 0, 1, 240],
    label: 'default',
    layerSchemaId: 'risco_hidrologico',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [255, 255, 255, 255],
    label: 'default',
    layerSchemaId: 'setores_subsetores',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [255, 255, 255, 255],
    label: 'default',
    layerSchemaId: 'subprefeitura',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [183, 183, 183, 240],
    label: 'default',
    layerSchemaId: 'subprefeitura',
  },
  {
    color: [183, 183, 183, 240],
    label: 'default',
    layerSchemaId: 'subprefeitura',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [0, 0, 0, 255],
    label: 'default',
    layerSchemaId: 'sujeicao_a_alagamentos',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [133, 32, 12, 240],
    label: 'default',
    layerSchemaId: 'sujeicao_a_alagamentos',
  },
  {
    color: [133, 32, 12, 240],
    label: 'default',
    layerSchemaId: 'sujeicao_a_alagamentos',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [255, 255, 255, 255],
    label: 'default',
    layerSchemaId: 'terras_indigenas',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [191, 144, 0, 240],
    label: 'default',
    layerSchemaId: 'terras_indigenas',
  },
  {
    color: [191, 144, 0, 240],
    label: 'default',
    layerSchemaId: 'terras_indigenas',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [255, 255, 255, 255],
    label: 'default',
    layerSchemaId: 'terrenos_marginais_aos_cursos_dagua_navegaveis',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [241, 194, 50, 240],
    label: 'default',
    layerSchemaId: 'terrenos_marginais_aos_cursos_dagua_navegaveis',
  },
  {
    color: [241, 194, 50, 240],
    label: 'default',
    layerSchemaId: 'terrenos_marginais_aos_cursos_dagua_navegaveis',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [255, 255, 255, 255],
    label: 'default',
    layerSchemaId: 'tombamentos-areas',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [255, 165, 0, 240],
    label: 'default',
    layerSchemaId: 'tombamentos-areas',
  },
  {
    color: [255, 165, 0, 240],
    label: 'default',
    layerSchemaId: 'tombamentos-areas',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [255, 255, 255, 255],
    label: 'default',
    layerSchemaId: 'tombamentos-envoltorias-de-imoveis',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [247, 217, 103, 240],
    label: 'default',
    layerSchemaId: 'tombamentos-envoltorias-de-imoveis',
  },
  {
    color: [247, 217, 103, 240],
    label: 'default',
    layerSchemaId: 'tombamentos-envoltorias-de-imoveis',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [255, 255, 255, 255],
    label: 'default',
    layerSchemaId: 'tombamentos-imoveis',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [249, 255, 0, 240],
    label: 'default',
    layerSchemaId: 'tombamentos-imoveis',
  },
  {
    color: [249, 255, 0, 240],
    label: 'default',
    layerSchemaId: 'tombamentos-imoveis',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [255, 255, 255, 255],
    label: 'default',
    layerSchemaId: 'zoneamento_geral',
    type: LayerSchemaColorTypeEnum.LINE,
  },
  {
    color: [255, 255, 255, 255],
    label: 'default',
    layerSchemaId: 'zoneamento_lei_16402_18177',
    type: LayerSchemaColorTypeEnum.LINE,
  },
];

export const layerSchemas: LayerSchema[] = [
  {
    id: 'aguas_correntes_estimadas',
    name: 'Águas Correntes Estimadas',
    origin:
      'https://geoserver.slui.dev/geoserver/slui/wms?LAYERS=slui%3Aaguas_correntes_estimadas&FORMAT=image%2Fjpeg&TRANSPARENT=true',
    isActive: true,
    type: LayerSchemaTypeEnum.CustomWMSLayer,
    isVisible: false,
    canEditFeature: false,
    minZoom: null,
    getTextColorPropName: null,
    getFillColorPropName: null,
    getLineColorPropName: null,
    groupId: 'areas_publicas',
  },
  {
    id: 'aguas_correntes_ou_dormentes',
    name: 'Águas Correntes ou Dormentes',
    origin:
      'https://geoserver.slui.dev/geoserver/slui/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=slui:aguas_correntes_ou_dormentes&maxFeatures=10000&outputFormat=json&srsName=EPSG:4326',
    isActive: true,
    type: LayerSchemaTypeEnum.GeoJsonLayer,
    isVisible: false,
    canEditFeature: false,
    minZoom: null,
    getTextColorPropName: null,
    getFillColorPropName: null,
    getLineColorPropName: null,
    groupId: 'areas_publicas',
  },
  {
    id: 'areas_contaminadas',
    name: 'Áreas Contaminadas',
    origin:
      'https://geoserver.slui.dev/geoserver/slui/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=slui:areas_contaminadas&maxFeatures=10000&outputFormat=json&srsName=EPSG:4326',
    isActive: true,
    type: LayerSchemaTypeEnum.GeoJsonLayer,
    isVisible: false,
    canEditFeature: false,
    minZoom: null,
    getTextColorPropName: null,
    getFillColorPropName: null,
    getLineColorPropName: null,
    groupId: 'ambiental',
  },
  {
    id: 'distrito_municipal',
    name: 'Distritos',
    origin: '/distritos.json',
    isActive: true,
    type: LayerSchemaTypeEnum.GeoJsonLayer,
    isVisible: true,
    canEditFeature: false,
    minZoom: null,
    getTextColorPropName: null,
    getFillColorPropName: null,
    getLineColorPropName: null,
    groupId: null,
    clickAction: {
      action: LayerSchemaClickActionEnum.SetZoom,
      params: {
        zoom: 17.1,
      },
    },
    properties: {
      stroked: true,
      filled: true,
      pointType: 'circle+text',
      pickable: true,
      wireframe: true,
      getLineWidth: 12,
      getPointRadius: 12,
      getTextAnchor: 'middle',
      getElevation: -10,
      getTextSize: 12,
      autoHighlight: true,
      highlightColor: [153, 203, 255, 140],
      maxZoom: 17,
    },
  },
  {
    id: 'eixos',
    name: 'Eixos',
    origin:
      'https://geoserver.slui.dev/geoserver/slui/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=slui:eixos&maxFeatures=10000&outputFormat=json&srsName=EPSG:4326',
    isActive: true,
    type: LayerSchemaTypeEnum.GeoJsonLayer,
    isVisible: false,
    canEditFeature: false,
    minZoom: null,
    getTextColorPropName: 'nm_perimetro_divisao_pde',
    getFillColorPropName: 'nm_perimetro_divisao_pde',
    getLineColorPropName: 'nm_perimetro_divisao_pde',
    groupId: 'macrozoneamento',
  },
  {
    id: 'lotes',
    name: 'Lotes',
    origin:
      'https://geoserver.slui.dev/geoserver/slui/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=slui%3Aview_lote_cidadao&maxFeatures=10000&outputFormat=json&srsName=EPSG:4326',
    isActive: true,
    type: LayerSchemaTypeEnum.Stream,
    isVisible: true,
    canEditFeature: false,
    minZoom: 17,
    getTextColorPropName: null,
    getFillColorPropName: null,
    getLineColorPropName: null,
    groupId: null,
    properties: {
      stroked: false,
      filled: true,
      pointType: 'circle+text',
      pickable: true,
      extruded: true,
      wireframe: true,
      getLineWidth: 20,
      getPointRadius: 0,
      getTextSize: 12,
      autoHighlight: true,
      highlightColor: [252, 252, 255, 150],
      getElevation: `(allotment) => {
        const { qt_area_construida, qt_area_terreno } =
          allotment?.properties || {};
        if (!qt_area_construida || !qt_area_terreno) return 0;

        return (qt_area_construida / qt_area_terreno) * 2 * 3;
      }`,
    },
  },
  {
    id: 'macroareas',
    name: 'Macroáreas',
    origin:
      'https://geoserver.slui.dev/geoserver/slui/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=slui:macroareas&maxFeatures=10000&outputFormat=json&srsName=EPSG:4326',
    isActive: true,
    type: LayerSchemaTypeEnum.GeoJsonLayer,
    isVisible: false,
    canEditFeature: false,
    minZoom: null,
    getTextColorPropName: 'nm_perimetro_divisao_pde',
    getFillColorPropName: 'nm_perimetro_divisao_pde',
    getLineColorPropName: 'nm_perimetro_divisao_pde',
    groupId: 'macrozoneamento',
  },
  {
    id: 'macrozonas',
    name: 'Macrozonas',
    origin:
      'https://geoserver.slui.dev/geoserver/slui/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=slui:macrozonas&maxFeatures=10000&outputFormat=json&srsName=EPSG:4326',
    isActive: true,
    type: LayerSchemaTypeEnum.GeoJsonLayer,
    isVisible: false,
    canEditFeature: false,
    minZoom: null,
    getTextColorPropName: 'nm_perimetro_divisao_pde',
    getFillColorPropName: 'nm_perimetro_divisao_pde',
    getLineColorPropName: 'nm_perimetro_divisao_pde',
    groupId: 'macrozoneamento',
  },
  {
    id: 'minianel_viario',
    name: 'Minianel Viário',
    origin:
      'https://geoserver.slui.dev/geoserver/slui/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=slui:minianel_viario&maxFeatures=10000&outputFormat=json&srsName=EPSG:4326',
    isActive: true,
    type: LayerSchemaTypeEnum.GeoJsonLayer,
    isVisible: false,
    canEditFeature: false,
    minZoom: null,
    getTextColorPropName: null,
    getFillColorPropName: null,
    getLineColorPropName: null,
    groupId: 'urbanistico',
  },
  {
    id: 'parques_unidades_conservacao',
    name: 'Parques e Unidades de Conservação',
    origin:
      'https://geoserver.slui.dev/geoserver/slui/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=slui:parques_unidades_de_conservacao_e_apa&maxFeatures=10000&outputFormat=json&srsName=EPSG:4326',
    isActive: false,
    type: LayerSchemaTypeEnum.GeoJsonLayer,
    isVisible: false,
    canEditFeature: false,
    minZoom: null,
    getTextColorPropName: null,
    getFillColorPropName: null,
    getLineColorPropName: null,
    groupId: 'areas_publicas',
  },
  {
    id: 'pracas_e_canteiros',
    name: 'Praças e Canteiros',
    origin:
      'https://geoserver.slui.dev/geoserver/slui/wms?LAYERS=slui%3Apracas_e_canteiros&FORMAT=image%2Fjpeg&TRANSPARENT=true',
    isActive: true,
    type: LayerSchemaTypeEnum.CustomWMSLayer,
    isVisible: false,
    canEditFeature: false,
    minZoom: null,
    getTextColorPropName: null,
    getFillColorPropName: null,
    getLineColorPropName: null,
    groupId: 'areas_publicas',
  },
  {
    id: 'represas',
    name: 'Represas',
    origin:
      'https://geoserver.slui.dev/geoserver/slui/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=slui:represas&maxFeatures=10000&outputFormat=json&srsName=EPSG:4326',
    isActive: false,
    type: LayerSchemaTypeEnum.GeoJsonLayer,
    isVisible: false,
    canEditFeature: false,
    minZoom: null,
    getTextColorPropName: null,
    getFillColorPropName: null,
    getLineColorPropName: null,
    groupId: 'areas_publicas',
  },
  {
    id: 'restricoes_geotecnicas',
    name: 'Restrições Geotécnicas',
    origin:
      'https://geoserver.slui.dev/geoserver/slui/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=slui:restricoes_geotecnicas&maxFeatures=10000&outputFormat=json&srsName=EPSG:4326',
    isActive: true,
    type: LayerSchemaTypeEnum.GeoJsonLayer,
    isVisible: false,
    canEditFeature: false,
    minZoom: null,
    getTextColorPropName: null,
    getFillColorPropName: null,
    getLineColorPropName: null,
    groupId: 'seguranca',
  },
  {
    id: 'risco_geologico',
    name: 'Risco Geológico',
    origin:
      'https://geoserver.slui.dev/geoserver/slui/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=slui:risco_geologico&maxFeatures=10000&outputFormat=json&srsName=EPSG:4326',
    isActive: true,
    type: LayerSchemaTypeEnum.GeoJsonLayer,
    isVisible: false,
    canEditFeature: false,
    minZoom: null,
    getTextColorPropName: null,
    getFillColorPropName: null,
    getLineColorPropName: null,
    groupId: 'seguranca',
  },
  {
    id: 'risco_hidrologico',
    name: 'Risco Hidrológico',
    origin:
      'https://geoserver.slui.dev/geoserver/slui/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=slui:risco_hidrologico&maxFeatures=10000&outputFormat=json&srsName=EPSG:4326',
    isActive: true,
    type: LayerSchemaTypeEnum.GeoJsonLayer,
    isVisible: false,
    canEditFeature: false,
    minZoom: null,
    getTextColorPropName: 'tx_tipo_processo',
    getFillColorPropName: null,
    getLineColorPropName: null,
    groupId: 'seguranca',
  },
  {
    id: 'setores_subsetores',
    name: 'Setores e Subsetores',
    origin:
      'https://geoserver.slui.dev/geoserver/slui/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=slui:setores_e_subsetores&maxFeatures=10000&outputFormat=json&srsName=EPSG:4326',
    isActive: true,
    type: LayerSchemaTypeEnum.GeoJsonLayer,
    isVisible: false,
    canEditFeature: false,
    minZoom: null,
    getTextColorPropName: 'subsetor',
    getFillColorPropName: 'subsetor',
    getLineColorPropName: 'subsetor',
    groupId: 'macrozoneamento',
  },
  {
    id: 'subprefeitura',
    name: 'Subprefeituras',
    origin:
      'https://geoserver.slui.dev/geoserver/slui/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=slui:subprefeitura&maxFeatures=10000&outputFormat=json&srsName=EPSG:4326',
    isActive: true,
    type: LayerSchemaTypeEnum.GeoJsonLayer,
    isVisible: false,
    canEditFeature: false,
    minZoom: null,
    getTextColorPropName: null,
    getFillColorPropName: null,
    getLineColorPropName: null,
    groupId: null,
  },
  {
    id: 'sujeicao_a_alagamentos',
    name: 'Sujeição a Alagamentos',
    origin:
      'https://geoserver.slui.dev/geoserver/slui/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=slui:sujeicao_a_alagamentos&maxFeatures=10000&outputFormat=json&srsName=EPSG:4326',
    isActive: true,
    type: LayerSchemaTypeEnum.CustomWMSLayer,
    isVisible: false,
    canEditFeature: false,
    minZoom: null,
    getTextColorPropName: null,
    getFillColorPropName: null,
    getLineColorPropName: null,
    groupId: 'seguranca',
  },
  {
    id: 'terras_indigenas',
    name: 'Terras Indígenas',
    origin:
      'https://geoserver.slui.dev/geoserver/slui/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=slui:terras_indigenas&maxFeatures=10000&outputFormat=json&srsName=EPSG:4326',
    isActive: true,
    type: LayerSchemaTypeEnum.GeoJsonLayer,
    isVisible: false,
    canEditFeature: false,
    minZoom: null,
    getTextColorPropName: null,
    getFillColorPropName: null,
    getLineColorPropName: null,
    groupId: null,
  },
  {
    id: 'terrenos_marginais_aos_cursos_dagua_navegaveis',
    name: "Terrenos Marginais aos Cursos D'Água Navegáveis",
    origin:
      'https://geoserver.slui.dev/geoserver/slui/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=slui:terrenos_marginais_aos_cursos_dagua_navegaveis&maxFeatures=10000&outputFormat=json&srsName=EPSG:4326',
    isActive: true,
    type: LayerSchemaTypeEnum.GeoJsonLayer,
    isVisible: false,
    canEditFeature: false,
    minZoom: null,
    getTextColorPropName: null,
    getFillColorPropName: null,
    getLineColorPropName: null,
    groupId: 'areas_publicas',
  },
  {
    id: 'tombamentos-areas',
    name: 'Ambientais e Urbanísticos',
    origin:
      'https://geoserver.slui.dev/geoserver/slui/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=slui:tombamentos-areas&maxFeatures=10000&outputFormat=json&srsName=EPSG:4326',
    isActive: true,
    type: LayerSchemaTypeEnum.GeoJsonLayer,
    isVisible: false,
    canEditFeature: false,
    minZoom: null,
    getTextColorPropName: null,
    getFillColorPropName: null,
    getLineColorPropName: null,
    groupId: 'tombamento',
  },
  {
    id: 'tombamentos-envoltorias-de-imoveis',
    name: 'Envoltorias de Imóveis',
    origin:
      'https://geoserver.slui.dev/geoserver/slui/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=slui:tombamentos-envoltorias-de-imoveis&maxFeatures=10000&outputFormat=json&srsName=EPSG:4326',
    isActive: true,
    type: LayerSchemaTypeEnum.GeoJsonLayer,
    isVisible: false,
    canEditFeature: false,
    minZoom: null,
    getTextColorPropName: null,
    getFillColorPropName: null,
    getLineColorPropName: null,
    groupId: 'tombamento',
  },
  {
    id: 'tombamentos-imoveis',
    name: 'Imóveis',
    origin:
      'https://geoserver.slui.dev/geoserver/slui/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=slui:tombamentos-imoveis&maxFeatures=10000&outputFormat=json&srsName=EPSG:4326',
    isActive: true,
    type: LayerSchemaTypeEnum.GeoJsonLayer,
    isVisible: false,
    canEditFeature: false,
    minZoom: null,
    getTextColorPropName: null,
    getFillColorPropName: null,
    getLineColorPropName: null,
    groupId: 'tombamento',
  },
  {
    id: 'zeis_pde',
    name: 'ZEIS - Lei nº 16.050/14',
    origin:
      'https://geoserver.slui.dev/geoserver/slui/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=slui:ZEIS_(PDE)&maxFeatures=10000&outputFormat=json&srsName=EPSG:4326',
    isActive: true,
    type: LayerSchemaTypeEnum.GeoJsonLayer,
    isVisible: false,
    canEditFeature: false,
    minZoom: null,
    getTextColorPropName: 'cd_zoneamento_perimetro',
    getFillColorPropName: 'cd_zoneamento_perimetro',
    getLineColorPropName: 'cd_zoneamento_perimetro',
    groupId: 'urbanistico',
  },
  {
    id: 'zoneamento_geral',
    name: 'Urbano Geral',
    origin:
      'https://geoserver.slui.dev/geoserver/slui/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=slui:zoneamento_geral&maxFeatures=10000&outputFormat=json&srsName=EPSG:4326',
    isActive: true,
    type: LayerSchemaTypeEnum.GeoJsonLayer,
    isVisible: false,
    canEditFeature: false,
    minZoom: null,
    getTextColorPropName: 'nm_perimetro_divisao_pde',
    getFillColorPropName: 'nm_perimetro_divisao_pde',
    getLineColorPropName: 'nm_perimetro_divisao_pde',
    groupId: 'macrozoneamento',
  },
  {
    id: 'zoneamento_lei_16402_18177',
    name: 'Zoneamento - Lei nº 16.402/16+18.177/24',
    origin:
      'https://geoserver.slui.dev/geoserver/slui/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=slui:zoneamento&maxFeatures=10000&outputFormat=json&srsName=EPSG:4326',
    isActive: true,
    type: LayerSchemaTypeEnum.Stream,
    isVisible: false,
    canEditFeature: false,
    minZoom: 17,
    getTextColorPropName: 'cd_zoneamento_perimetro',
    getFillColorPropName: 'cd_zoneamento_perimetro',
    getLineColorPropName: 'cd_zoneamento_perimetro',
    groupId: 'urbanistico',
  },
];
