name: Deploy Urbis Legis

on:
  push:
    branches:
      - master
  # pull_request:
  #   types: [opened, synchronize, reopened, closed]
  #   branches:
  #     - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy urbis-legis
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build urbis-legis
        run: pnpm turbo run build --filter=@open-urbis/legis
        env:
          VITE_API_URL: https://api.mapa.urbis.prefeitura.sp.gov.br
          VITE_OIDC_AUTHORITY: https://api.mapa.urbis.prefeitura.sp.gov.br/auth/oidc
          VITE_OIDC_CLIENT_ID: 94a86322-269e-44df-803a-534c0382215d
          VITE_OIDC_REDIRECT_URI: /callback
          VITE_OIDC_SILENT_REDIRECT_URI: /silent-renew.html

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_GLACIER_0ABCED210 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          ###### Repository/Build Configurations ######
          app_location: "apps/legis/dist"
          api_location: ""
          output_location: ""
          skip_app_build: true
          ###### End of Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_GLACIER_0ABCED210 }}
          action: "close"
